CREATE TABLE ERS_REIMBURSEMENT(
REIMB_ID        NUMBER CONSTRAINT ERS_REIMBURSEMENT_PK PRIMARY KEY,
REIMB_AMOUNT    NUMBER,
REIMB_SUBMITTED TIMESTAMP,
REIMB_RESOLVED  TIMESTAMP,
REIMB_DESC      VARCHAR2(250),
REIMB_RECEIPT   BLOB,
REIMB_AUTHOR    NUMBER,
REIMB_RESOLVER  NUMBER,
REIMB_STATUS_ID NUMBER,
REIMB_TYPE_ID   NUMBER,

CONSTRAINT ERS_USERS_FK_AUTH FOREIGN KEY (REIMB_AUTHOR)REFERENCES ERS_USERS (ERS_USERS_ID) ON DELETE CASCADE,
CONSTRAINT ERS_USERS_FK_RESLVR FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS (ERS_USERS_ID) ON DELETE CASCADE,
CONSTRAINT ERS_REIMBURSEMENT_STATUS_FK FOREIGN KEY (REIMB_STATUS_ID)REFERENCES ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID)ON DELETE CASCADE,
CONSTRAINT ERS_REIMBURSEMENT_TYPE_FK FOREIGN KEY(REIMB_TYPE_ID)REFERENCES ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID) ON DELETE CASCADE
);

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
REIMB_STATUS_ID NUMBER CONSTRAINT REIMB_STATUS_PK PRIMARY KEY,
REIMB_STATUS    VARCHAR2(10)
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE(
REIMB_TYPE_ID   NUMBER CONSTRAINT REIMB_TYPE_PK PRIMARY KEY,
REIMB_TYPE      VARCHAR2(10)
);

CREATE TABLE ERS_USERS(
ERS_USERS_ID    NUMBER CONSTRAINT ERS_USERS_PK PRIMARY KEY,
ERS_USERNAME    VARCHAR2(50) UNIQUE,
ERS_PASSWORD    VARCHAR2(50),
USER_FIRST_NAME VARCHAR2(100),
USER_LAST_NAME  VARCHAR2(100),
USER_EMAIL      VARCHAR2(150) UNIQUE,
USER_ROLE_ID    NUMBER,
CONSTRAINT USER_ROLES_FK FOREIGN KEY (USER_ROLE_ID) REFERENCES ERS_USER_ROLES (ERS_USER_ROLE_ID) ON DELETE CASCADE
);

CREATE TABLE ERS_USER_ROLES(
ERS_USER_ROLE_ID    NUMBER CONSTRAINT ERS_USER_ROLES_PK PRIMARY KEY,
USER_ROLE           VARCHAR2(10)
);

create or replace PROCEDURE newReimbursement(
reimbid IN NUMBER, reimbamount IN NUMBER, reimbsubmit IN TIMESTAMP,
reimbdesc IN VARCHAR2,riembauthor IN VARCHAR2, riembstatusID IN NUMBER,
riembtypeID IN NUMBER)
IS
BEGIN
    INSERT INTO ERS_REIMBURSEMENT(REIMB_ID, REIMB_AMOUNT, REIMB_SUBMITTED,
    REIMB_DESC, REIMB_AUTHOR,REIMB_STATUS_ID, REIMB_TYPE_ID) 
    VALUES (reimbid,reimbamount, reimbsubmit,reimbdesc, riembauthor,riembstatusID,riembtypeID);
END;
/

CREATE OR REPLACE PROCEDURE newUser(
username IN VARCHAR2, pw IN VARCHAR2, fn IN VARCHAR2,
ln IN VARCHAR2, email IN VARCHAR2)
IS
BEGIN
    INSERT INTO ERS_USERS(ERS_USERNAME, ERS_PASSWORD, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL)
    VALUES (username, pw, fn, ln, email);
END;
/

DROP TABLE ERS_USER_ROLES;
DROP TABLE ERS_REIMBURSEMENT;
DROP TABLE ERS_REIMBURSEMENT_STATUS;
DROP TABLE ERS_REIMBURSEMENT_TYPE;
DROP TABLE ERS_USER_ROLES;
DROP TABLE ERS_USERS;