--DROP TABLE USER_ROLES;
CREATE TABLE USER_ROLES(
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE VARCHAR2(10)
);

--DROP TABLE REIMBURSEMENT_STATUS;
CREATE TABLE REIMBURSEMENT_STATUS(
    STATUS_ID NUMBER PRIMARY KEY,
    STATUS    VARCHAR2(10)
)

CREATE TABLE REIMBURSEMENT_TYPE(
    TYPE_ID NUMBER PRIMARY KEY,
    TYPE    VARCHAR(10)
)

--DROP TABLE USERS;
CREATE TABLE USERS(
    USERS_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE,
    PWORD VARCHAR2(50),
    FIRST_NAME VARCHAR2(100),
    LAST_NAME VARCHAR2(100),
    EMAIL VARCHAR2(150) UNIQUE,
    ROLE_ID NUMBER REFERENCES USER_ROLES(ROLE_ID)
    ON DELETE CASCADE
);

CREATE TABLE REIMBURSEMENT(
    REIMB_ID    NUMBER PRIMARY KEY,
    AMOUNT      NUMBER,
    SUBMITTED   TIMESTAMP,
    RESOLVED    TIMESTAMP,
    DESCRIPTION VARCHAR2(250),
    RECEIPT     BLOB,
    AUTHOR      NUMBER REFERENCES USERS(USERS_ID) ON DELETE CASCADE,
    RESOLVER    NUMBER REFERENCES USERS(USERS_ID) ON DELETE CASCADE,
    STATUS_ID   NUMBER REFERENCES REIMBURSEMENT_STATUS(STATUS_ID) ON DELETE CASCADE,
    TYPE_ID     NUMBER REFERENCES REIMBURSEMENT_TYPE(TYPE_ID) ON DELETE CASCADE
);





















INSERT INTO ers_user_roles VALUES(10, 'janitor');
INSERT INTO ers_users VALUES (9,'BOB','io','lad','ao',10);

select * 
from ers_user_roles;
--union all
select * 
from ers_users;

delete
from ers_user_roles;