-- Employees table DDL
--DROP TABLE EMPLOYEES;
CREATE TABLE EMPLOYEES (
    id          NUMBER(11) PRIMARY KEY,
    name        VARCHAR2(25) NOT NULL,
    role        VARCHAR2(25) NOT NULL,
    insert_time DATE DEFAULT NULL
);

CREATE SEQUENCE  EMPLOYEE_SEQ
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER EMPLOYEE_TRIGGER
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW

BEGIN
  SELECT EMPLOYEE_SEQ.NEXTVAL 
  INTO :new.ID
  FROM DUAL;
END;

--DROP TABLE STUDENTS;
--TRUNCATE TABLE STUDENTS;

CREATE TABLE STUDENTS (
  id            NUMBER(11) NOT NULL PRIMARY KEY,
  first_name    VARCHAR2(45) DEFAULT NULL,
  last_name     VARCHAR2(45) DEFAULT NULL,
  email         VARCHAR2(45) DEFAULT NULL
);

-- Students table DDL
--DROP SEQUENCE STUDENT_SEQ;
CREATE SEQUENCE STUDENT_SEQ
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1
START WITH 1;

CREATE OR REPLACE TRIGGER STUDENT_TRIGGER
BEFORE INSERT ON STUDENTS
FOR EACH ROW

BEGIN
  SELECT STUDENT_SEQ.NEXTVAL 
  INTO :new.ID
  FROM DUAL;
END;